---
ID: "7c6d0770-ca95-4f29-bffb-d440165cc019"
Parent: "094cc389-21ca-485b-a9ba-7af82800b617"
Template: "094cc389-21ca-485b-a9ba-7af82800b617"
Path: /sitecore/templates/Gymster/Data Template/About Us/__Standard Values
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: business/32x32/businessman.png
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 300
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250202T052719Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
