---
ID: "378ccaec-f868-4225-a204-fcc51a527360"
Parent: "8a111fe2-2421-41be-a7c5-042868f13e90"
Template: "8a111fe2-2421-41be-a7c5-042868f13e90"
Path: /sitecore/templates/Gymster/Data Template/Carousel/__Standard Values
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: apps/32x32/Slideshow.png
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250209T065429Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
