---
ID: "66647e8f-38d6-437a-97fd-0a865ffd4a04"
Parent: "e6014e63-ac20-43ad-a291-a163accb1b7a"
Template: "e6014e63-ac20-43ad-a291-a163accb1b7a"
Path: /sitecore/templates/Gymster/Base Template/_Navigation/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250216T235846Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "72d141be-d43f-4c91-90b9-dabc1d4583f0"
      Hint: Show In Navigation
      Type: Checkbox
      Value: 1
